version: "3.1"

services:
  # express:
  #   container_name: live-chat-api
  #   depends_on:
  #     - mongo
  #   dockerfile: ./live-chat-server/Dockerfile
  #   ports:
  #     - 3001:3001

  mongo:
    container_name: live-chat-mongo
    image: mongo
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db

  mongo-express:
    container_name: live-chat-mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo

volumes:
  mongo-data:
