const LOG_IN = 'LOG_IN'
const LOG_OUT = 'LOG_OUT'
const SET_LAST_MESSAGE = 'SET_LAST_MESSAGE'

const SET_TOKEN = 'SET_TOKEN'
const REMOVE_TOKEN = 'REMOVE_TOKEN'
const SET_USER = 'SET_USER'
const REMOVE_USER = 'REMOVE_USER'

const TOGGLE_MODAL = 'TOGGLE_MODAL'
const OPEN_MODAL = 'OPEN_MODAL'
const CLOSE_MODAL = 'CLOSE_MODAL'

const ADD_CONVERSATION = 'ADD_CONVERSATION'
const REMOVE_CONVERSATION = 'REMOVE_CONVERSATION'

export {
    LOG_IN,
    LOG_OUT,
    SET_LAST_MESSAGE,
    SET_TOKEN,
    REMOVE_TOKEN,
    SET_USER,
    REMOVE_USER,
    ADD_CONVERSATION,
    REMOVE_CONVERSATION,
    TOGGLE_MODAL,
    OPEN_MODAL,
    CLOSE_MODAL,
}
